### PR TITLE
bugfix/#75-send-a-request-item-not-corresponded-to-mockup

### LINKED ISSUE #75: [Home page] The “Send a Request” item in the home page “How it works” block is not corresponded to the mockup.
[Home page] The “Send a Request” item in the home page “How it works” block is not corresponded to the mockup.
The “Send a Request” item in the student registration option at the home page “How it works” block is not corresponded to the mockup.
**Environment:** Windows 10 x64
Microsoft Edge 112.0.1722.48
Google Chrome 112.0.5615.122
MacOS Big Sur 11.7.3 
Safari 16.3 (16614.4.6.11.6, 16614)

**Reproducible:** always.
Build found: commit 79f5645

**Preconditions:**
The user is not logged in.

**Steps to reproduce:**
1. Open the client site.
2. Click on the “How it works” button on the home page header.
3. Take a look at the home page “How it works” block.

**Actual result:**
The “Send a Request” item in the student registration option at the home page “How it works” block is not corresponded to the mockup.

**Expected result**
The “Send a Request” item in the student registration option at the home page “How it works” block is matched to the mockup.

**Attachments:**
Home page  The “Send a Request” item in the home page “How it works” block is not corresponded to the mockup

### PR DESCRIPTION
**Pull request by BodiaPutiak**
The titles font size has been changed.

### CODE REVIEW

**Comment by docia** [comment]
Before receiving approval, please add the following to the PR: 
- Assignees(add yourself)
- Labels(click the gear icon next to it and chose labels)
- Projects(Space2Study-02)
- Development(also click the gear Icon and you may type "75" to find the issue)

**Review by Olenka-Hryk — COMMENTED** [review]
I'm not sure why the fontSize and fontWeight in the title were changed. Maybe **'Send a Request'** should match the mockup, considering the issue #75 ?

**Comment by BodiaPutiak** [comment]
Those are the styles in the mockup where the fontSize is 24px:
Screenshot 2024-04-30 155507
The element currently has variant h6:
Screenshot 2024-04-30 155546
Which has those styles:
Screenshot 2024-04-30 155558

**Comment by BodiaPutiak** [comment]
> Before receiving approval, please add the following to the PR:
> 
> * Assignees(add yourself)
> * Labels(click the gear icon next to it and chose labels)
> * Projects(Space2Study-02)
> * Development(also click the gear Icon and you may type "75" to find the issue)

Linked the issue under the Development link
Screenshot 2024-04-30 160226

**Review by docia — APPROVED** [review]

**Review by Olenka-Hryk — APPROVED** [review]

**Review by m6xcom — APPROVED** [review]

**Review by vlad-khrychov — APPROVED** [review]

**Pull request merged**
